### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by F33RNI** [Draskown/Light-Cone#1]
Files required to run the project are missing in this repo:
- 150.jpg
- Test.jpg
- 50.jpg

The paths to these files are specified in file `Circles.cpp` on lines 21-32.

```cpp
if (i == 1) {
	image = imread("D:/Other/Desktop/Ucheba/HS/QIA/Project/150.jpg");
	lower = 66;
	upper = 87;
	size = 0.07;
}
else if (i == 2) {
	image = imread("D:/Other/Desktop/Ucheba/HS/QIA/Project/Test.jpg");
	lower = 87;
	size = 0.05;
} else
	image = imread("D:/Other/Desktop/Ucheba/HS/QIA/Project/50.jpg");
```

Also, there is no test video source `D:/Other/Desktop/Ucheba/HS/QIA/Project/Video.mp4` in the repo.

```cpp
string FILENAME = "D:/Other/Desktop/Ucheba/HS/QIA/Project/Video.mp4";
```

**Comment by Draskown** [comment]
Truth has been told, but I kinda don't give a sh!t anymore hahah

**Comment by F33RNI** [comment]
![d20e956c668fc2ceef11adedb314047f](https://user-images.githubusercontent.com/39090123/177006171-331f7957-bee3-4e88-9ffe-7442e62406c7.jpg)
